service: icomp-submission-count
plugins:
  - serverless-offline
  - serverless-prune-plugin
provider:
  name: aws
  stage: dev
  environment:
    REGION: ${opt:region, self:custom.defaultRegion}
    ENVIRONMENT: dev
    DEFAULT_AWS_REGION: us-east-1
  runtime: nodejs20.x
  region: ${opt:region, self:custom.defaultRegion}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:UpdateItem
        - Lambda:InvokeFunction
      Resource:
        - "arn:aws:dynamodb:us-east-2:024669054950:table/*"
        - "arn:aws:s3:::attachment-icomp-dev"
        - "arn:aws:s3:::attachment-icomp-dev/*"
        - "arn:aws:s3:::ocr-doc-demo-acord"
        - "arn:aws:s3:::ocr-doc-demo-acord/*"
        - "arn:aws:dynamodb:us-east-1:024669054950:table/StatesWithZipCode"
        - "arn:aws:dynamodb:us-east-1:024669054950:table/ClassCodeDescriptionAndEligibility"
        - "arn:aws:dynamodb:us-east-1:024669054950:table/StatesWithZipCode"

custom:
  defaultRegion: us-east-1
  serverless-offline:
    httpPort: 3000
functions:
  app:
    handler: lambda.handler
    timeout: 30
    events:
      - httpApi: "*"
